### ISSUE TITLE
Files references not cleanud up

### ISSUE THREAD

**Issue by mhicauber** [entur/ninkasi#2]
When using the "clean" button, imported files references listed in the "Migrate data" tab are not cleared, whereas files are physically deleted on the filesystem => Error in marduk when trying to revalidate a listed file.

![image](https://user-images.githubusercontent.com/1476276/37026623-3b597aca-212f-11e8-8ba6-3d0b585d81e5.png)

**Comment by mhicauber** [comment]
I'll try to fix it when I get some time.

**Comment by seanes** [comment]
`{timetableAdmi}/clean` is async, so our only guarantee is that the cleaning job has started.

Provided we would want to poll periodically to render current state in file list, we would also have to empty outbound files (if any are added). 

As always, a pull request is very welcome!

**Comment by erlendnils1** [comment]
Files are not deleted in the file system by choosing clean. Not on the chouette disk and not in marduk GCS storage.

Only the choutte referential schema in the db is cleaned. After cleaning you need to reimport a new dataset before you can validate anything. If you try to execute validate in an empty dataspace (button #2 in screenshot) you will be getting an error in the chouette validation report. This should ideally tell you "Dataspace is empty" or something to that effect, but is probably gibberish. Is this what you are referring to?

This has, however, nothing to do with the file list in the "Migrate data" tab in ninkasi. These files are kept i marduks GCS storage and may be re-imported by selecting a file and choosing 'IMPORT'.

**Comment by mhicauber** [comment]
nope that's not what I wanted to say.
I had the feeling that the "migrate data" files were deleted on the file
system (we use local storage, not GCS), but kept appearing in the "import
file" list.

Might be wrong, I'll check it again. Sorry for the noise. Please keep the
issue open I'll close it or comment it out.

2018-03-08 9:24 GMT+01:00 erlendnils1 <notifications@github.com>:
